FROM amazoncorretto:17-alpine-jdk
MAINTAINER emre-gurkan@hotmail.com
COPY build/libs/atom-applicant-service-0.0.1-SNAPSHOT.jar atom-applicant-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "./atom-applicant-service-0.0.1-SNAPSHOT.jar"]