server:
  port: ${SERVER_PORT:28080}

spring:
  application:
    name: atom-applicant-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://druvagavlwichafiphe4idatiflfruwr:3ufo94cadatra8rlspudupogo2tecraf@0.0.0.0:27017}
      database: LTyKnDJ
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVER_URL:localhost:9092}


eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://${eureka.instance.hostname}:${EUREKA_PORT:8761}/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
