version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  dNOvuT1_job-listings:
    image: mysql:latest
    ports:
      - '13306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=3ufo94cadatra8rlspudupogo2tecraf
      - MYSQL_USER=druvagavlwichafiphe4idatiflfruwr
      - MYSQL_PASSWORD=3ufo94cadatra8rlspudupogo2tecraf
      - MYSQL_DATABASE=dNOvuT1

  uUGiUAB_profiles:
    image: mysql:latest
    ports:
      - '23306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=3ufo94cadatra8rlspudupogo2tecraf
      - MYSQL_USER=druvagavlwichafiphe4idatiflfruwr
      - MYSQL_PASSWORD=3ufo94cadatra8rlspudupogo2tecraf
      - MYSQL_DATABASE=uUGiUAB

  RguU3oS_keycloak:
    image: mysql:latest
    networks:
      - keycloak
    environment:
      - MYSQL_ROOT_PASSWORD=3ufo94cadatra8rlspudupogo2tecraf
      - MYSQL_USER=druvagavlwichafiphe4idatiflfruwr
      - MYSQL_PASSWORD=3ufo94cadatra8rlspudupogo2tecraf
      - MYSQL_DATABASE=RguU3oS

  openldap:
    image: 'bitnami/openldap:latest'
    environment:
      LDAP_ROOT: dc=obss,dc=com
      LDAP_ADMIN_USERNAME: ievuqu1eiquehabaeleefoo8Zae1eeWeej2iubahvoo1thoqu1ieNgith3Leizaiw4phaosh7deeficiewiuviejeeyohghohkahfieP0aithelooVieke6oongahng4
      LDAP_ADMIN_PASSWORD: shoonieY8heisah0aequiCien4mi6in4choh8OhJeeng2xoo8caKuigheinauj8wathaeYaich5Aing0osuhohHaijiem9thai4uo0Yoorie5sesech9eemahmohY4phaiz1oo2KiDeegaeng7theethie2ooheex6sielaic2ootooy7ahvoh0ahL5ohxohfooy0aiphahphachuu4Eerein8Waecaixao5Gaceachah2yaegoiphee0ohrohna
      LDAP_CUSTOM_LDIF_DIR: /ldifs
    networks:
      - keycloak
    volumes:
      - '/home/egurkan/projects/obss/learnings/examples/atom/resource:/ldifs'

  keycloak:
    image: 'quay.io/keycloak/keycloak:22.0.1'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://RguU3oS_keycloak:3306/RguU3oS
      KC_DB_USERNAME: druvagavlwichafiphe4idatiflfruwr
      KC_DB_PASSWORD: 3ufo94cadatra8rlspudupogo2tecraf
    command: start-dev
    networks:
      - keycloak
    ports:
      - '4080:8080'
    depends_on:
      - RguU3oS_keycloak
      - openldap

networks:
  keycloak:
    driver: bridge