FROM amazoncorretto:17-alpine-jdk
MAINTAINER emre-gurkan@hotmail.com
COPY build/libs/atom-gateway-0.0.1-SNAPSHOT.jar atom-gateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "./atom-gateway-0.0.1-SNAPSHOT.jar"]