server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: atom-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: atom-job-listing-service
          uri: lb://atom-job-listing-service
          predicates:
            - Path=/api/v2/job-listings/**
          filters:
            - StripPrefix=3
        - id: atom-application-service
          uri: lb://atom-application-service
          predicates:
            - Path=/api/v2/applications/**
          filters:
            - StripPrefix=3
        - id: atom-applicant-service
          uri: lb://atom-applicant-service
          predicates:
            - Path=/api/v2/applicants/**
          filters:
            - StripPrefix=3

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://${eureka.instance.hostname}:${EUREKA_PORT:8761}/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
