FROM amazoncorretto:17-alpine-jdk
MAINTAINER emre-gurkan@hotmail.com
COPY build/libs/atom-service-registry-0.0.1-SNAPSHOT.jar atom-service-registry-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "./atom-service-registry-0.0.1-SNAPSHOT.jar"]