FROM amazoncorretto:17-alpine-jdk
MAINTAINER emre-gurkan@hotmail.com
COPY build/libs/atom-application-service-0.0.1-SNAPSHOT.jar atom-application-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "./atom-application-service-0.0.1-SNAPSHOT.jar"]